language: node_js
node_js:
- node
branches:
  only:
  - develop
cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
script:
- ng lint
- ng build --prod
deploy:
  provider: s3
  access_key_id:
    secure: UmgdSZ6hOPR0gmjYg1tyPD9jbf9HKOztEyUwyIGwSGykM64k6nr03OJuqWiodT7hBbWk01eNJdf0+5T3R8EzkDVQbObS74My4ZEfOtzRrIPRxZyT3mXtHpAlDoS9dGzSGgVXyQfo55EeIS022AMejaYjLMQz9zc5hMdxMqq2KKThfSZWPd1Vx6VxCe95Lc1wK/Ldp7uszFLSIpR3y5drP9gZ7xUSg7u/L8DrhlZRgKX40VwjAHZgeV0OPD5xEbA54conKUrubx5K8EXlQlCYGlTtKzf9PzmBy7q1iVd9Rc9Itb9DdfBlTHnv7vhwHsq6lUe2yP8h7SuHLuVwYRYheDtTXqVvJUF10a6IwKB1ySDXklXoB0gympTfBMGpvM43E2/XcW/HrgdSWKDrqIMtXwG4SnITQHF5JRRNkH5DWBCHKZFygpopRt9t0tGiAnG9zSXsbCCaoqt32auL/xCCi+mGY8RkvzCEiBQZXsEsEt16Ej1GR+GycwEh2vFB/7SZWw3uM5pafB/0SrU0xHUd2qgm/bytiA0ae1vdeSZ2Ux599ILusR7lvkgW8HTL3Zsxkx55WccMe1NtsWrxA5oIo3txmvX6PLNo7vwWXY81ExvRqvloXJAqJHn16Oaw3ydrm2W7lYnv6rPs6EaMArSntAXaIZB3DaocaUQUEcCQSIw=
  secret_access_key:
    secure: O+rBO1oaZZmyp/Q6MrtJzc3cvYSKfPnVZaGzFI20izAZyNbZQgHUN7l+0hj1n3//887H/vrk/X250p3k/NrAT4DwJNsaTAs+wIOcVFKVXMr9FwNWG9AP3ERn/eFko5KHLFRi7Uz8z9WlkqA5/qHON9S0+JZhLXeGPIyKhMHzYZVpZ4r1wnqk4iLnJEAI6TvL6e+gwt7M2emWarAWsHxtQ8GdqDnzRCkQxKhRgNjtp6aaz25pL5sfpFgtilTD73gtBGqYD08BRoWRKuyUXPDzWP/KPaz3z67iY9jdTkAIXaeGF4sCXGQP7aln5viuA/iapb0ALyT1Hd3FTPT2xNWJVRSBf1mK7qSziBvTJFVKrwtRzu2tTH4zbR5ZxGTPXB9MZaGcuE3s+phFrKnR24pa46GjnHBirC80JVNkIlI60PS1ccLFoxKGL654n5kDqnXcoOS98Bep8bIuclr2nwOgaVNuT/mZfC6zHiRSZ/cxkZeGImSwHydXFP11iKs9fHuYtQA+iDSDlHQxpKT9L+nXP/z6FwNUOQfZNcOZM7860j1P0Gqyy9Vaspx9pEqCcr77gubOZ/JAIRr7t2MIKxjlKWqWVTT6DbBcHMV57hNKQdX4fdFB7JUKQCZcTw6o8zcg3HyPnNu386ttjcNiTlXjo//NW4Xdfp/52PXzWOuei3s=
  bucket: climate.reedmartz.com
  skip_cleanup: true
  local_dir: dist/climate
  on:
    branch: develop
notifications:
  email:
    on_failure: change
    on_success: always
